/**
 * Prepares a local-only American-English neural voice for the Android APK.
 *
 * Nothing generated by this script is committed: the vendor artifacts are large,
 * while the upstream revisions below are immutable. `android:debug` and CI
 * reproduce the exact APK payload from these URLs.
 *
 * Runtime: Apache-2.0 (sherpa-onnx v1.13.4)
 * Model package: see the bundled LICENSE after extraction.  Keep its notices in
 * the in-app third-party notice before publishing a production store build.
 */
import { existsSync, mkdirSync, renameSync, rmSync, statSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { execFileSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';

const projectRoot = dirname(dirname(fileURLToPath(import.meta.url)));
const androidRoot = join(projectRoot, 'android');
const cacheRoot = join(androidRoot, '.offline-tts-cache');
const appRoot = join(androidRoot, 'app', 'src', 'main');
const assetsRoot = join(appRoot, 'assets');
const jniRoot = join(appRoot, 'jniLibs');
const kotlinRoot = join(appRoot, 'java', 'com', 'k2fsa', 'sherpa', 'onnx');
const modelRoot = join(assetsRoot, 'kokoro-en-v0_19');

const runtimeUrl =
  'https://github.com/k2-fsa/sherpa-onnx/releases/download/v1.13.4/sherpa-onnx-v1.13.4-android.tar.bz2';
const bindingsUrl =
  'https://raw.githubusercontent.com/k2-fsa/sherpa-onnx/v1.13.4/android/SherpaOnnxAar/sherpa_onnx/src/main/java/com/k2fsa/sherpa/onnx/Tts.kt';
const modelRepo = 'https://huggingface.co/csukuangfj/kokoro-en-v0_19';
const huggingFaceApi = 'https://huggingface.co/api/models/csukuangfj/kokoro-en-v0_19';
const modelRevision = '92805c4';
const modelFileUrl = `${modelRepo}/resolve/${modelRevision}/model.onnx?download=true`;
const voicesFileUrl = `${modelRepo}/resolve/${modelRevision}/voices.bin?download=true`;
const tokensFileUrl = `${modelRepo}/resolve/${modelRevision}/tokens.txt?download=true`;

function log(message: string) {
  process.stdout.write(`[offline-neural-tts] ${message}\n`);
}

function run(command: string, args: string[], cwd = projectRoot) {
  execFileSync(command, args, { cwd, stdio: 'inherit', env: process.env });
}

function download(url: string, destination: string) {
  mkdirSync(dirname(destination), { recursive: true });
  if (existsSync(destination) && statSync(destination).size > 0) return;
  const partial = `${destination}.part`;
  log(`Downloading ${url.split('/').at(-1)}. This happens once and may take a few minutes.`);
  run('curl', [
    '--fail',
    '--location',
    '--http1.1',
    '--retry',
    '12',
    '--retry-all-errors',
    '--retry-delay',
    '2',
    '--continue-at',
    '-',
    '--output',
    partial,
    url
  ]);
  renameSync(partial, destination);
}

function extract(archive: string, destination: string) {
  const staging = `${destination}.staging`;
  rmSync(staging, { recursive: true, force: true });
  mkdirSync(staging, { recursive: true });
  run('tar', ['-xjf', archive, '--strip-components=1', '-C', staging]);
  rmSync(destination, { recursive: true, force: true });
  renameSync(staging, destination);
}

function fetchJson<T>(url: string): T {
  const output = execFileSync(
    'curl',
    ['--fail', '--location', '--http1.1', '--retry', '3', '--retry-all-errors', url],
    { cwd: projectRoot, env: process.env }
  );
  return JSON.parse(output.toString()) as T;
}

function main() {
  mkdirSync(cacheRoot, { recursive: true });
  const runtimeArchive = join(cacheRoot, 'sherpa-onnx-v1.13.4-android.tar.bz2');
  if (!existsSync(join(jniRoot, 'arm64-v8a', 'libsherpa-onnx-jni.so'))) {
    download(runtimeUrl, runtimeArchive);
    extract(runtimeArchive, jniRoot);
  }
  mkdirSync(kotlinRoot, { recursive: true });
  const bindings = join(kotlinRoot, 'Tts.kt');
  if (!existsSync(bindings)) {
    log('Downloading the Apache-2.0 Android bindings.');
    run('curl', ['--fail', '--location', '--retry', '3', '--output', bindings, bindingsUrl]);
  }
  if (process.env.OPSLINGO_SKIP_MODEL_DOWNLOAD === '1') {
    log('Skipping model payload only for local native compilation verification.');
    return;
  }
  mkdirSync(modelRoot, { recursive: true });
  download(modelFileUrl, join(modelRoot, 'model.onnx'));
  download(voicesFileUrl, join(modelRoot, 'voices.bin'));
  download(tokensFileUrl, join(modelRoot, 'tokens.txt'));
  const dataRoot = join(modelRoot, 'espeak-ng-data');
  if (!existsSync(join(dataRoot, '.opslite-complete'))) {
    log('Fetching the bundled offline English pronunciation data.');
    const requiredDataFiles = new Set([
      'espeak-ng-data/en_dict',
      'espeak-ng-data/intonations',
      'espeak-ng-data/phondata',
      'espeak-ng-data/phondata-manifest',
      'espeak-ng-data/phonindex',
      'espeak-ng-data/phontab'
    ]);
    const dataFiles = fetchJson<Array<{ type: string; path: string }>>(
      `${huggingFaceApi}/tree/${modelRevision}/espeak-ng-data?recursive=true&expand=false&limit=1000`
    ).filter(
      (entry) =>
        entry.type === 'file' &&
        (requiredDataFiles.has(entry.path) || entry.path.startsWith('espeak-ng-data/lang/gmw/'))
    );
    for (const entry of dataFiles) {
      download(
        `${modelRepo}/resolve/${modelRevision}/${entry.path.split('/').map(encodeURIComponent).join('/')}`,
        join(modelRoot, entry.path)
      );
    }
    writeFileSync(join(dataRoot, '.opslite-complete'), `${modelRevision}\n`);
  }
  writeFileSync(
    join(modelRoot, 'OPSLINGO_NOTICE.txt'),
    'Bundled for offline neural speech. See the upstream repository and its license notices.\n'
  );
  const minimumModelBytes = 250 * 1024 * 1024;
  if (statSync(join(modelRoot, 'model.onnx')).size < minimumModelBytes) {
    throw new Error(
      'The offline neural model is unexpectedly small; refusing to build an incomplete APK.'
    );
  }
  log('Offline neural American-English voice is ready for APK packaging.');
}

main();
